Lint, Format and Tidy action on push to all branches

diff --git a/project b/project
--- a/project
+++ b/project
@@ -21,8 +21,7 @@ function configure() {
         echo "pre-commit successfully installed"
     fi
 
-
-    pre-commit install
+    pre-commit install || fail "Failed to activate pre-commit"
 }
 
 function newRelease() {
